-- 1. MANAGER Table
CREATE TABLE MANAGER (
    SSN VARCHAR(11),                -- Kept as VARCHAR to preserve leading zeros
    NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    PRIMARY KEY (SSN)
);

-- 2. CLIENT Table
CREATE TABLE CLIENT (
    CARDNUMBER VARCHAR(20) NOT NULL,
	EXPIR VARCHAR(100) NOT NULL,
	PIN VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100),
    NAME VARCHAR(100),
    PRIMARY KEY (EMAIL),
    ROADNAME VARCHAR(100) NOT NULL,
    NUMBER VARCHAR(10) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
	FOREIGN KEY (CARDNUMBER, EXPIR, PIN, ROADNAME, NUMBER, CITY) REFERENCES CREDITCARD(CARDNUMBER, EXPIR, PIN, ROADNAME, NUMBER, CITY),
    FOREIGN KEY (ROADNAME, NUMBER, CITY) REFERENCES ADDRESS(ROADNAME, NUMBER, CITY) 
);
-- 3. ADDRESS Table
CREATE TABLE ADDRESS (
    ROADNAME VARCHAR(100),
    NUMBER VARCHAR(10),
    CITY VARCHAR(100),
    ZIPCODE VARCHAR(10),           -- Kept as VARCHAR to handle ZIP+4 and leading zeros
    PRIMARY KEY (ROADNAME, NUMBER, CITY)
);
-- 4. DRIVER Table
CREATE TABLE DRIVER (
    NAME VARCHAR(100),
    PRIMARY KEY (NAME),
    ROADNAME VARCHAR(100) NOT NULL,
    NUMBER VARCHAR(10) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    FOREIGN KEY (ROADNAME, NUMBER, CITY) REFERENCES ADDRESS(ROADNAME, NUMBER, CITY) 
);

-- 5. CAR Table
CREATE TABLE CAR (
    CARID VARCHAR(10),
    MODEL VARCHAR(100),
    MAKE VARCHAR(100),
    YEAR INT,
    PRIMARY KEY (CARID)
);

-- 6. MODEL Table (depends on CAR)
CREATE TABLE MODEL (
    COLOR VARCHAR(50),
    CONSTRUCTIONYEAR INT,
    AUTO BOOLEAN,
    MANUAL BOOLEAN,
    MODELID VARCHAR(50),
    CARID VARCHAR(10),
    PRIMARY KEY (MODELID, CARID),
    FOREIGN KEY (CARID) REFERENCES CAR(CARID)
);
-- 7.RENT Table
CREATE TABLE RENT (
    RENTID INT,
    DATE DATE,
    PRIMARY KEY (RENTID),
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    CARID VARCHAR(10) NOT NULL,
    MODELID VARCHAR(50) NOT NULL,
    FOREIGN KEY (NAME) REFERENCES DRIVER,
    FOREIGN KEY (EMAIL) REFERENCES CLIENT,
    FOREIGN KEY(MODELID,CARID) REFERENCES MODEL(MODELID,CARID)
);

-- 8. CREDITCARD Table
CREATE TABLE CREDITCARD (
    CARDNUMBER VARCHAR(20),        -- Stored as string for leading zeros and long numbers
    PRIMARY KEY (CARDNUMBER),
	EXPIR VARCHAR(100) NOT NULL,
	PIN VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    ROADNAME VARCHAR(100) NOT NULL,
    NUMBER VARCHAR(10) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    FOREIGN KEY (EMAIL) REFERENCES CLIENT,
    FOREIGN KEY (ROADNAME, NUMBER, CITY) REFERENCES ADDRESS(ROADNAME, NUMBER, CITY)
);

-- 9. REVIEW Table (depends on DRIVER)
CREATE TABLE REVIEW (
    RATING INT,
    REVIEWID INT,
    MESSAGE VARCHAR(500),
    NAME VARCHAR(100),  
    PRIMARY KEY (REVIEWID, NAME),
    EMAIL VARCHAR(100) NOT NULL,
	FOREIGN KEY (EMAIL) REFERENCES CLIENT,
    FOREIGN KEY (NAME) REFERENCES DRIVER(NAME)
);



-- 10. DRIVES Table (depends on DRIVER and MODEL)
CREATE TABLE DRIVES (
    NAME VARCHAR(100),
    CARID VARCHAR(10),
    MODELID VARCHAR(50),
    PRIMARY KEY (NAME, MODELID, CARID),
    FOREIGN KEY (NAME) REFERENCES DRIVER(NAME),
    FOREIGN KEY (MODELID, CARID) REFERENCES MODEL(MODELID, CARID)
);

-- 11. LIVES Table (depends on CLIENT and ADDRESS)
CREATE TABLE LIVES (
    EMAIL VARCHAR(100),
    ROADNAME VARCHAR(100),
    NUMBER VARCHAR(10),
    CITY VARCHAR(100),
    PRIMARY KEY (EMAIL, ROADNAME, NUMBER, CITY),
    FOREIGN KEY (EMAIL) REFERENCES CLIENT(EMAIL),
    FOREIGN KEY (ROADNAME, NUMBER, CITY) REFERENCES ADDRESS(ROADNAME, NUMBER, CITY)
);
